name = "FluxProgress"
uuid = "653ea0b7-b6f4-4bcb-9f3f-fb1d491c5e74"
authors = ["soyukke <soyukke@gmail.com>"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
